/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebayerror;

/**
 *
 * @author Jackie Lambrini
 */
public class Calcu extends javax.swing.JFrame {

    /**
     * Creates new form Calcu
     */
    public Calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPantalla = new javax.swing.JTextField();
        btnBin = new javax.swing.JButton();
        btnDec = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDiez = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnDoce = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnTrece = new javax.swing.JButton();
        btnCatorce = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnBotonD = new javax.swing.JRadioButton();
        btnbotonDEC = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPantalla);
        txtPantalla.setBounds(44, 16, 194, 20);

        btnBin.setText("BIN");
        getContentPane().add(btnBin);
        btnBin.setBounds(51, 54, 49, 23);

        btnDec.setText("DEC");
        getContentPane().add(btnDec);
        btnDec.setBounds(136, 54, 53, 23);

        btn1.setText("1");
        getContentPane().add(btn1);
        btn1.setBounds(44, 107, 39, 23);

        btn2.setText("2");
        getContentPane().add(btn2);
        btn2.setBounds(101, 107, 39, 23);

        btn3.setText("3");
        getContentPane().add(btn3);
        btn3.setBounds(150, 107, 39, 23);

        btn4.setText("4");
        getContentPane().add(btn4);
        btn4.setBounds(44, 148, 39, 23);

        btn5.setText("5");
        getContentPane().add(btn5);
        btn5.setBounds(101, 148, 39, 23);

        btn6.setText("6");
        getContentPane().add(btn6);
        btn6.setBounds(150, 148, 39, 23);

        btn7.setText("7");
        getContentPane().add(btn7);
        btn7.setBounds(44, 182, 39, 23);

        btn8.setText("8");
        getContentPane().add(btn8);
        btn8.setBounds(101, 182, 39, 23);

        btn9.setText("9");
        getContentPane().add(btn9);
        btn9.setBounds(150, 182, 39, 23);

        btnDiez.setText("A");
        getContentPane().add(btnDiez);
        btnDiez.setBounds(44, 211, 39, 23);

        btnB.setText("B");
        getContentPane().add(btnB);
        btnB.setBounds(101, 211, 39, 23);

        btnDoce.setText("C");
        getContentPane().add(btnDoce);
        btnDoce.setBounds(150, 211, 39, 23);

        btnD.setText("D");
        getContentPane().add(btnD);
        btnD.setBounds(44, 252, 39, 23);

        btnTrece.setText("E");
        btnTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreceActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrece);
        btnTrece.setBounds(101, 252, 39, 23);

        btnCatorce.setText("F");
        getContentPane().add(btnCatorce);
        btnCatorce.setBounds(150, 252, 39, 23);

        btnCero.setText("0");
        getContentPane().add(btnCero);
        btnCero.setBounds(101, 293, 39, 23);

        btnResta.setText("-");
        getContentPane().add(btnResta);
        btnResta.setBounds(213, 107, 41, 23);

        btnSuma.setText("+");
        getContentPane().add(btnSuma);
        btnSuma.setBounds(213, 148, 41, 23);

        btnIgual.setText("=");
        getContentPane().add(btnIgual);
        btnIgual.setBounds(213, 182, 41, 23);
        getContentPane().add(btnBotonD);
        btnBotonD.setBounds(62, 79, 21, 21);
        getContentPane().add(btnbotonDEC);
        btnbotonDEC.setBounds(150, 79, 21, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/18AD0A55-545B-4BFD-A29D-3BD7630D5719.JPEG"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void btnTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn1;
    public static javax.swing.JButton btn2;
    public static javax.swing.JButton btn3;
    public static javax.swing.JButton btn4;
    public static javax.swing.JButton btn5;
    public static javax.swing.JButton btn6;
    public static javax.swing.JButton btn7;
    public static javax.swing.JButton btn8;
    public static javax.swing.JButton btn9;
    public static javax.swing.JButton btnB;
    public static javax.swing.JButton btnBin;
    public static javax.swing.JRadioButton btnBotonD;
    public static javax.swing.JButton btnCatorce;
    public static javax.swing.JButton btnCero;
    public static javax.swing.JButton btnD;
    public static javax.swing.JButton btnDec;
    public static javax.swing.JButton btnDiez;
    public static javax.swing.JButton btnDoce;
    public static javax.swing.JButton btnIgual;
    public static javax.swing.JButton btnResta;
    public static javax.swing.JButton btnSuma;
    public static javax.swing.JButton btnTrece;
    public static javax.swing.JRadioButton btnbotonDEC;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
